services:
    chatterino-proxy:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghcr.io/mrchuw/chatterino-proxy:latest
        container_name: chatterino-proxy
        ports:
            - "8000:8000"
        volumes:
            - ./config.json:/config.json:ro
        restart: unless-stopped
